services:
  # Backend service
  - type: web
    name: backend
    runtime: node
    buildCommand: cd back && npm ci && npm run build
    startCommand: cd back && npm start
    plan: starter
    env: node
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  # Frontend service  
  - type: web
    name: frontend
    runtime: node
    buildCommand: cd front && npm ci && npm run build
    startCommand: cd front && npm start
    plan: starter
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: NEXT_PUBLIC_RPC_URL
        value: https://mainnet.helius-rpc.com/?api-key=afaeaa09-73d8-4eaf-bffa-c30ea047ec58
      - key: NEXT_PUBLIC_SERVER_URL
        value: wss://backend

  # Static file service for assets (if needed)
  - type: web
    name: assets
    runtime: node
    buildCommand: cd front && npm ci
    startCommand: cd front && npx serve -s public/assets -l 4001 --cors
    plan: starter
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001
